runtime: python312
entrypoint: gunicorn -b :$PORT main_app:app
instance_class: F4_1G
basic_scaling:
  max_instances: 1
  idle_timeout: 5m  # Shuts down instance after 5 minutes of inactivity
handlers:
  - url: /.*
    script: auto
env_variables:
  GCS_BUCKET_NAME: 'clean-scrape-audio-files'
  GOOGLE_CLOUD_PROJECT: 'resewrch-agent'
  FIRESTORE_DATABASE: 'clean-scrape-articles'
  FFMPEG_PATH: './ffmpeg'
