runtime: python312
entrypoint: gunicorn -b :$PORT main_app:app
instance_class: F4
handlers:
  - url: /.*
    script: auto
env_variables:
  GCS_BUCKET_NAME: 'clean-scrape-audio-files'
  GOOGLE_CLOUD_PROJECT: 'resewrch-agent'
  FIRESTORE_DATABASE: 'clean-scrape-articles'
  FFMPEG_PATH: './ffmpeg'
